FORMAT: 1A

# Sphere

## Group Areas

## GET /areas?limit&offset

List all areas.

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"
                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## POST /areas

Create a new area.

+ Request (application/json)

        {
            "name": "Area 1",
            "region": {
                "url": "/region/5"
            },
            "depot": {
                "name": "Grand Central Station",
                "latitude": 0.0,
                "longitude": 0.0,
                "url": "/depot/2",
            },
            "url": "/area/1"
        }

+ Response 200 (application/json)

## GET /areas/{id}

Retrieve an area.

+ Parameters

    + id (number, required) - ID of the Area.

+ Response 200 (application/json)

        {
            "name": "Area 1",
            "region": {
                "name": "Pemba",
                "url": "/region/5"

            },
            "depot": {
                "name": "Grand Central Station",
                "latitude": 0.0,
                "longitude": 0.0,
                "url": "/depot/2",
            },
            "url": "/area/1"
        }

## PUT /areas/{id}

Update an area.

+ Request Update JSON Message (application/json)

        { "message": "All your base are belong to us." }

+ Response 204 (application/json)

### Delete an area [DELETE]

+ Response 200 (application/json)

## Complaints Collection [/complaints?limit&offset]

### List all complaints [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Complaints [/complaints/{id}]

## Customers Collection [/customers]

### List all customers [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Customers [/customers/{id}]

## Customer Registrations Collection [/customer_registrations?limit&offset]

### List all customer registrations [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Customer Registrations [/customer_registrations/{id}]

## Depots Collection [/depots]

### List all depots [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Depots [/depots/{id}]

## Dispatches Collection [/dispatches?limit&offset]

### List all dispatches [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Dispatches [/dispatches/{id}]

## Orders Collection [/orders?limit&offset]

### List all orders [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Orders [/orders/{id}]

## Price Categories Collection [/price_categories]

### List all price categories [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Price Categories [/price_categories/{id}]

## Products Collection [/products?limit&offset]

### List all products [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Products [/products/{id}]

## Regions Collection [/regions]

### List all regions [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Regions [/regions/{id}]

### Retrieve a region [GET]

+ Response 200 (application/json)

        {
            "name": "Pemba",
            "url": "/region/1"
        }

## Stock Adjustments [/stock_adjustments]

### Adjust stock for a product [POST]

+ Response 200 (application/json)

## Tasks Collection [/tasks?limit&offset]

### List all tasks [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Tasks [/tasks/{id}]

## Vehicles Collection [/vehicles?limit&offset]

### List all vehicles [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

    + offset (number, optional) - Offset from which to start returning items.
        + Default: `0`

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Vehicles [/vehicles/{id}]

## Weight Classes Collection [/weight_classes]

### List all weight classes [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                },
                "url": "/area/1"
            }
        ]

## Weight Classes [/weight_classes/{id}]

