FORMAT: 1A

# Sphere

# Group Area

## Area Collection [/areas]

### List all areas [GET]

+ Response 200 (application/json)

        [
            {
                "url": "/area/1"
                "name": "Area 1",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                }
            },
            {
                "url": "/area/2"
                "name": "Area 2",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                }
            },
            {
                "url": "/area/3"
                "name": "Area 3",
                "region": {
                    "name": "Pemba",
                    "url": "/region/5"

                },
                "depot": {
                    "name": "Grand Central Station",
                    "latitude": 0.0,
                    "longitude": 0.0,
                    "url": "/depot/2",
                }
            }
        ]

## Area [/areas/{id}]
        
### retrieve an area [GET]

+ Response 200 (application/json)

        {
            "url": "/area/1"
            "name": "Area 1",
            "region": {
                "name": "Pemba",
                "url": "/region/5"

            },
            "depot": {
                "name": "Grand Central Station",
                "latitude": 0.0,
                "longitude": 0.0,
                "url": "/depot/2",
            }
        }

### Create a new area [POST]

+ Response 200 (application/json)


# Group Complaint

# Group Customer

# Group Customer Registration

# Group Depot

# Group Dispatch

# Group Order

# Group Price Category

# Group Product

# Group Region

# Group Task

# Group Vehicle

# Group Weight Class
